sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "6"
cache:
  - node_modules
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install mgit2 lerna @ckeditor/ckeditor5-dev-tests
  - mgit bootstrap --repository-resolver=git-https-resolver.js
  - lerna bootstrap
script:
  - node_modules/.bin/ckeditor5-dev-tests --reporter=dots
